### ISSUE TITLE
Amazon2.exe corrupt (not a PE binary)

### ISSUE THREAD

**Issue by belgab1980** [yosukes-dev/AmazonWSL#13]
just downloaded the release 2.0.20210721.2 and foudn that the Amazon2.exe is broken.
I've used the previous release one to finish the installation.

Gabriele

**Comment by yosukes-dev** [comment]
Thank you for reporting.
Fixed version uploaded.
https://github.com/yosukes-dev/AmazonWSL/releases/tag/2.0.20210721.2
