### ISSUE TITLE
Cannot find a valid baseurl for repo: amzn2-core/2/x86_64

### ISSUE THREAD

**Issue by anilsamuel** [yosukes-dev/AmazonWSL#16]
-bash-4.2# yum update -y
Loaded plugins: ovl, priorities
Could not retrieve mirrorlist https://amazonlinux.default.amazonlinux.com/2/core/latest/x86_64/mirror.list error was
12: Timeout on https://amazonlinux.default.amazonlinux.com/2/core/latest/x86_64/mirror.list: (28, 'Resolving timed out after 5001 milliseconds')

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64

**Comment by yosukes-dev** [comment]
It originally ran fine in the verification environment, but at least the latest release binaries have not experienced such an event.

```bash
-bash-4.2# yum update -y
Loaded plugins: ovl, priorities
amzn2-core                                                                   | 3.7 kB  00:00:00
(1/3): amzn2-core/2/x86_64/group_gz                                          | 2.5 kB  00:00:00
(2/3): amzn2-core/2/x86_64/updateinfo                                        | 476 kB  00:00:00
(3/3): amzn2-core/2/x86_64/primary_db                                        |  63 MB  00:00:11
No packages marked for update
-bash-4.2#
```
