### ISSUE TITLE
AWS AMI 2022

### ISSUE THREAD

**Issue by clarson** [yosukes-dev/AmazonWSL#19]
Has anyone started working on a build for Ami 2022?

https://docs.aws.amazon.com/linux/al2022/ug/get-started.html

I haven't tried and i'm not sure if it is possible with preview, but I'm assuming it is getting close to GA.

Thanks,
Chuck

**Comment by yosukes-dev** [comment]
Commit fd323054899e7f5f15a429282b7f15dd2fc945ea to Amazon Linux 2022 images.
