### ISSUE TITLE
Icon for Windows Terminal

### ISSUE THREAD

**Issue by bjorg** [yosukes-dev/AmazonWSL#2]
For the next release, maybe include the below PNG as an `AWS-icon.png` file. That way it could easily be added to the Windows Terminal profile.

<img width="256" alt="AWS-icon" src="https://user-images.githubusercontent.com/63682/76440363-fa04cd00-637a-11ea-8a5e-8a8ce757773c.png">

Here's also an example for the Windows Profile itself.
```json
{
    "guid": "{3dffc929-1f2e-44cc-8253-9635e0298f6b}",
    "hidden": false,
    "name": "Amazon Linux 2",
    "commandline": "wsl.exe -d Amazon2",
    "startingDirectory" : "C:\\",
    "icon": "C:\\Amazon2\\AWS-icon.png"
}
```

**Comment by yosukes-dev** [comment]
Since AmazonWSL uses [wsldl](https://github.com/yuk7/wsldl), installation-related functions depend on wsldl.
So you need to open the feature request on wsldl, not AmazonWSL.

**Comment by bjorg** [comment]
It doesn't need to be installed. Just part of the zip would be good enough.

**Comment by yosukes-dev** [comment]
OK.
Does that mean just including images as an option, right?
If so, you need to make sure that the original icon itself can be redistributed with the same license as the Amazon Linux distribution.

**Comment by bjorg** [comment]
Yes. I'll do some research.

**Comment by bjorg** [comment]
This one is very similar and has a free license:
http://www.iconarchive.com/show/simple-icons-by-danleech/aws-icon.html

The original I proposed requires a link back. Maybe in the ReadMe?
http://www.iconarchive.com/show/socialmedia-icons-by-uiconstock/AWS-icon.html

**Comment by yosukes-dev** [comment]
The second one looks better. 
I will add it and update `README.md`.
