### ISSUE TITLE
Determine correct version of Distro

### ISSUE THREAD

**Issue by genifycom** [yosukes-dev/AmazonWSL#3]
I followed the instructions and Amazon2 is the default

PS C:\WINDOWS\system32> wsl -l
Windows Subsystem for Linux Distributions:
Amazon2 (Default)

So to check the version, I used:

PS C:\WINDOWS\system32> wsl
-bash-4.2# uname -srm
Linux 4.4.0-18362-Microsoft x86_64
-bash-4.2#

Is this version correct for Amazon Linux?

Thanks

**Comment by genifycom** [comment]
Do you know where .bashrc is located for the Amazon WSL distro?

The default directory drop me into /mnt/c/WINDOWS/system32 which is dangerous

**Comment by genifycom** [comment]
cat /etc/os-release shows

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

So it looks like distro is good.

**Comment by yosukes-dev** [comment]
The kernel version depends on your Windows builds.

I close this issue because your question is for WSL, not for AmazonWSL.
