### ISSUE TITLE
Service command not found

### ISSUE THREAD

**Issue by uanid** [yosukes-dev/AmazonWSL#5]
When I run command `service docker start`
The console says `-bash: service: command not found`

How do I run service command?

I tried to search service binary to /usr/sbin, /sbin, /usr/bin, etc...
But I can't find the service binary anywhere.

**Comment by yosukes-dev** [comment]
> Amazon Linux 2 comes with the same benefits as Amazon Linux, but it adds some new capabilities:
> systemd: replacing SystemVinit

This means you have to use systemctl instead of the service command.
But currently systemd does not work with WSL.
So, you need to use a helper like [genie](https://github.com/arkane-systems/genie).

**Comment by yosukes-dev** [comment]
Please try the following steps.

>1 yum upgrade -y && yum update -y
>2 amazon-linux-extras install -y kernel-ng

https://github.com/yosukes-dev/AmazonWSL/issues/6#issuecomment-674526850

**Comment by volkancakil** [comment]
i have made few modifications on @shayne [wsl2-hacks](https://github.com/shayne/wsl2-hacks) repo to get systemd support on Amazon Linux.
Please follow this steps [WSL2 Amazon Linux systemd support](https://gist.github.com/volkancakil/6ceb0d6958cf6cc29970aa5f737c147e)

**Comment by uanid** [comment]
@volkancakil Great work!!
