### ISSUE TITLE
Service cmd doesn't load

### ISSUE THREAD

**Issue by jvargh** [yosukes-dev/AmazonWSL#6]
-bash-4.2# systemctl
Failed to get D-Bus connection: Operation not permitted

-bash-4.2# service
-bash: service: command not found

**Comment by yosukes-dev** [comment]
Please refer to #5 because this is duplicated with it.

**Comment by jvargh** [comment]
was able to get service to run after below 2 steps as suggested by link
    1  yum upgrade -y && yum update -y
    2  amazon-linux-extras install -y kernel-ng

https://www.youtube.com/watch?v=jEGXNY_vhd8
